#!/bin/bash

CURRENT_COMPILE="0"

# {1} - title
# {2} - message
function displayNotification() {
	if hash osascript 2>/dev/null; then
		osascript -e "display notification \"${2}\" with title \"${1}\""
	fi
}

function checkSuccessful() {
	displayNotification "Compile #${CURRENT_COMPILE}" "Compilation was successful."
	echo "--- COMPILE SUCCESSFUL ---"
}

function checkError() {
	displayNotification "Compile #${CURRENT_COMPILE}" "Compilation has failed!"
	tput bel
	echo "--- FAILED TO COMPILE ---"
}

# Increments the current compile counter,
# then prints its new value.
# Prints the date, and then runs cargo check.
function checkCode() {
	CURRENT_COMPILE=$(($CURRENT_COMPILE + 1))
	clear
	local DATE=`date +"%T"`
	echo "[${DATE}] CHECK #${CURRENT_COMPILE}"
	cargo check

	if [ $? -eq 0 ]; then
		checkSuccessful
	else
		checkError
	fi
}

# Reads a line from stdin, and then
# runs checkCode
function readAndCheckCode() {
	while read -d "" event;
	do
		checkCode
	done
}

checkCode

# Watches the src directory
# and Cargo.toml for changes,
# and pipes events through readAndCheckCode.
fswatch -0 -l 0.3 "src/" "Cargo.toml" | readAndCheckCode